name = "specsolid-newsletter"
main = "worker/src/index.js"
compatibility_date = "2026-08-01"

[vars]
ALLOWED_ORIGIN = "https://codigosintetico.specsolid.com"
SENDER_NAME = "Sergio Perez Ruiz"
SENDER_EMAIL = "sergio@specsolid.com"

[[d1_databases]]
binding = "DB"
database_name = "specsolid-newsletter-db"
database_id = "7e879a49-f3cb-48bd-a444-6bec443edeac"

[[r2_buckets]]
binding = "CHAPTERS_BUCKET"
bucket_name = "codigosintetico-chapters"
